name: maxwell_protocol
version: 0.6.5
description: The maxwell protocol implementation for dart.
homepage: https://github.com/maxwell-dev/maxwell-protocol-dart.git

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  protobuf: ^3.1.0

dev_dependencies:
  test: ^1.24.6
